### PR TITLE
Don't restore HTML title popover after destroying tip

### LINKED ISSUE #47: It should not set propperty title, when Tooltip is disabled
If I am using condition to enable/disable tooltip, it should not set `title` property to. What will happen, is even that condition is now met and tooltip is not active, system title still shows the the message. Only workaround is to use `html` prop.
screen shot 2018-01-15 at 14 09 18

### PR DESCRIPTION
**Pull request by nnnoel**
Fixes #47

### CODE REVIEW

**Comment by timminata** [comment]
Can we get this fix merged in? I'm having to avoid using title because of this.

**Comment by mbryla** [comment]
@tvkhoa

**Comment by aviklar10** [comment]
@tvkhoa  ?

**Comment by ATrogolo** [comment]
Hi @tvkhoa , 
could you merge this fix in the master branch please?
I need this fix .. I don't want to fork this project for a single line of code

Thanks

**Comment by fabioDG89** [comment]
Hi @tvkhoa, 
any news about the merge?
I'm also stuck and I can't use the component.

Thanks

**Comment by hayduas** [comment]
So.. it's been 3 years now, and nobody commits this fix? 
WTF?

**Comment by Zigonja** [comment]
We would really appreciate if this could be merged

**Review by heavensloop — APPROVED** [review]
LGTM!

**Comment by ATrogolo** [comment]
Does anyone would merge this?

**Review by umangbp — APPROVED** [review]

**Comment by aviklar10** [comment]
why closed ? isn't it an effective fix ?

**Pull request closed without merging**
