### PR TITLE
Custom tag element for tooltip trigger

### LINKED ISSUE #30: Custom HTML tag
I noticed `react-tippy` set the wrapper tag as a `div`, which gives some warning from React if used inside a `p` for example

screen shot 2017-10-16 at 5 44 09 pm

There could be a custom `Tag` feature (see an example here https://github.com/reactstrap/reactstrap/blob/master/src/Button.js#L72) so we could set it to something else (like a `span`) what do you think?

### LINKED ISSUE #64: div cannot appear as a descendant of p
Hi,

I have anchor tags inside paragraphs which are surrounded by Tooltip components. Tooltips work well but I receive the following error in console:

> validateDOMNesting(...): `<div>` cannot appear as a descendant of `<p>`.

I've tried replacing `<div>` tags with other HTML elements in the source file but no use. Either tooltip looks ugly or the document flow breaks. I can replace `<p>`s with `<div>`s to get rid of the error but it's semantically wrong because the content is supposed to be a paragraph.

Is there any known solution for this?

### PR DESCRIPTION
**Pull request by didoesdigital**
Add "tag" option for tooltip to choose HTML elements for tooltip target wrappers. This lets you use a `span` instead of a `div` and therefore put `<span>`s inside `<p>`s to avoid invalid markup and squash error messages.

Fixes: #30
Fixes: #64

### CODE REVIEW

**Comment by christophedebatz** [comment]
Can someone merge this PR please ?

**Comment by stk-dmitry** [comment]
@tvkhoa ping

**Comment by euanlau** [comment]
@anhvy mind taking a look?

**Comment by vilia** [comment]
Still waiting for this PR to be merged
@anhvy are there any estimation when it will be? Do you need any help?

**Comment by anhvy** [comment]
Sorry for late response. I'll resolve the conflict and merge this asap.

**Comment by didoesdigital** [comment]
Thanks @anhvy!

**Comment by anhvy** [comment]
Even this has been merged but we haven't bump it to latest version on npm-package. We're working setting up CI/CD to automate this step. Please stay tuned!

**Comment by dimaip** [comment]
@anhvy sorry for the ping, but are there any plans to release the new version with this fix?

**Comment by anhvy** [comment]
OMG. Time flies so fast. Sorry to have kept you waiting, I'll double-check it now

**Comment by anhvy** [comment]
@didoesdigital I checked and this fix is already included in version **1.4.0**

**Comment by dimaip** [comment]
Ohh thanks so much, I got confused by the releases section on github and missed the fact that there's already 1.4.0 

image

**Pull request merged**
