### PR TITLE
Add guards ( Issue #17 )

### PR DESCRIPTION
**Pull request by ZoharLiran**
Attempt to add guards to take care of issue 17
https://github.com/tvkhoa/react-tippy/issues/17

### CODE REVIEW

**Comment by phamtuan2993** [comment]
Thanks @ZoharLiran for your contribution,

This is have been solved on v1.2.3, please upgrade to match with new updates.

Thanks

**Comment by ZoharLiran** [comment]
Thank you for this new version. it indeed solved that error. but it seems like it is generating another error:
`[getPopperElement]: Element passed as the argument does not exist in the instance`

is this related to something you're working on already? or should I investigate further?

**Comment by ZoharLiran** [comment]
UPDATE - removing the `title` prop when `html` prop is present helped with this latest one.

**Comment by tvkhoa** [comment]
Because of conflicting, I manually merge your commits to master and rebuild again. Thank you

**Pull request closed without merging**
