### PR TITLE
Fixing "Cannot read property 'settings' of undefined" 

### PR DESCRIPTION
**Pull request by JonathanWi**
Adding some safeguards

### CODE REVIEW

**Comment by blaadje** [comment]
Very handy, thanks !

**Comment by sontek** [comment]
Please merge!! :)   I have to move away from react-tippy if this doesn't get fixed since its crashing our users

**Comment by sontek** [comment]
Actually, looks like you accidentally made the changes on the dist.  Want to make changes to the actual code to make it mergable?

**Comment by JonathanWi** [comment]
Sure, I'll get to it tonight :)

**Comment by bj0rge** [comment]
@tvkhoa Could you please take a look at it & merge it please? That would be awesome!

**Comment by kpennell** [comment]
@JonathanWi Is there a workaround for this in the meantime?

**Comment by kpennell** [comment]
I put these changes into my react-tippy.js. The error messages dissapear but the errors are still there.

**Comment by planetflash** [comment]
Any time estimate for this getting merged and released?

**Comment by phamtuan2993** [comment]
This have been fixed within new version 1.2.3, please check with it.

Thanks

**Pull request closed without merging**
